# Generated by Django 3.2.6 on 2021-08-18 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('roll_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('class_standard', models.CharField(max_length=30, null=True)),
                ('school_name', models.CharField(max_length=60, null=True)),
                ('mobile', models.CharField(max_length=30, null=True)),
                ('Address', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAcademics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maths', models.CharField(max_length=20, null=True)),
                ('Physics', models.CharField(max_length=20, null=True)),
                ('Chemistry', models.CharField(max_length=20, null=True)),
                ('Biology', models.CharField(max_length=20, null=True)),
                ('English', models.CharField(max_length=20, null=True)),
                ('roll_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student_crud.studentinfo')),
            ],
        ),
    ]
